# Configuração Dinâmica com Variáveis de Ambiente
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:db_estudos_mysql}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:sua_senha_local_de_teste}

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
