# Configuração Dinâmica com Variáveis de Ambiente
spring.datasource.url=jdbc:mysql://${DB_HOST:host}:3306/${DB_NAME:db_mysql}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
